name: build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq luarocks
      - name: Install pre-commit

      - name: Install LuaCheck
        run: luarocks install --local luacheck

      - name: Run LuaCheck using pre-commit on moreblocks
        run: |
          pre-commit run --all-files
          $HOME/.luarocks/bin/luacheck ./moreblocks

      - name: Run LuaCheck using pre-commit on stairsplus
        run: |
          pre-commit run --all-files
          $HOME/.luarocks/bin/luacheck ./stairsplus
